Updated releng/autorelease Project: neutron  811dfecc6053f9d27cd2e94e305423a21965ed6c
BUG #4026 : Missing key is getUuid. Supplied key is RouterKey []

When update router, it results in missing key for routers during encoding.
The following stack trace shows router case, but in theory this applies to
other resources.
data of update request doesn't include id, so the key isn't set. it should
be explicitly set by MD code before encoding.

POST to /controller/nb/v2/neutron/routers
DATA:
{
  "router": {
    "status": "ACTIVE",
    "external_gateway_info": null,
    "name": "router1",
    "gw_port_id": null,
    "admin_state_up": true,
    "routes": [],
    "tenant_id": "015ffea9d6094b9fbe465c4f1d76c636",
    "distributed": false,
    "id": "4e23aa01-f3aa-4eb8-83b2-58b59ee17fec"
  }
}

PUT to /controller/nb/v2/neutron/routers/4e23aa01-f3aa-4eb8-83b2-58b59ee17fec
DATA:
{
  "router": {
    "external_gateway_info": {
      "network_id": "a0ad7845-4434-4532-ba9e-3ac861a3d7c4",
      "enable_snat": true,
      "external_fixed_ips": [
        {
          "subnet_id": "08dda021-f395-411d-ad7f-89886c3b2678",
          "ip_address": "172.24.4.2"
        }
      ]
    },
    "name": "router1",
    "gw_port_id": "f46143b7-5eab-4e49-8dc3-094ce7d2cd54",
    "admin_state_up": true,
    "distributed": false,
    "routes": []
  }
}
---

> 2015-08-08 02:08:07,418 | WARN  | tp1647472839-767 | NeutronRouterInterface           | 374 - org.opendaylight.neutron.transcriber - 0.6.0.SNAPSHOT | Attempting to write neutron router without UUID
> 2015-08-08 02:08:07,419 | ERROR | tp1647472839-767 | ContainerResponse                | 195 - com.sun.jersey.jersey-server - 1.17.0 | The RuntimeException could not be mapped to a response, re-throwing to the HTTP container
> java.lang.IllegalArgumentException: All keys must be specified for class org.opendaylight.yang.gen.v1.urn.opendaylight.neutron.l3.rev141002.routers.attributes.routers.RouterKey. Missing key is getUuid. Supplied key is RouterKey []
>         at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
>         at org.opendaylight.yangtools.binding.data.codec.impl.ValueContext.getAndSerialize(ValueContext.java:46)
>         at org.opendaylight.yangtools.binding.data.codec.impl.IdentifiableItemCodec.serialize(IdentifiableItemCodec.java:124)
>         at org.opendaylight.yangtools.binding.data.codec.impl.IdentifiableItemCodec.serialize(IdentifiableItemCodec.java:31)
>         at org.opendaylight.yangtools.binding.data.codec.impl.KeyedListNodeCodecContext.addYangPathArgument(KeyedListNodeCodecContext.java:52)
>         at org.opendaylight.yangtools.binding.data.codec.impl.DataObjectCodecContext.bindingPathArgumentChild(DataObjectCodecContext.java:193)
>         at org.opendaylight.yangtools.binding.data.codec.impl.BindingCodecContext.getCodecContextNode(BindingCodecContext.java:127)
>         at org.opendaylight.yangtools.binding.data.codec.impl.BindingCodecContext.newWriter(BindingCodecContext.java:104)
>         at org.opendaylight.yangtools.binding.data.codec.impl.BindingNormalizedNodeCodecRegistry.toNormalizedNode(BindingNormalizedNodeCodecRegistry.java:102)
>         at org.opendaylight.controller.md.sal.binding.impl.BindingToNormalizedNodeCodec.toNormalizedNode(BindingToNormalizedNodeCodec.java:133)
>         at org.opendaylight.controller.md.sal.binding.impl.AbstractWriteTransaction.put(AbstractWriteTransaction.java:39)
>         at org.opendaylight.neutron.transcriber.AbstractNeutronInterface.updateMd(AbstractNeutronInterface.java:77)
>         at org.opendaylight.neutron.transcriber.NeutronRouterInterface.updateRouter(NeutronRouterInterface.java:107)
>         at org.opendaylight.neutron.northbound.api.NeutronRoutersNorthbound.updateRouter(NeutronRoutersNorthbound.java:294)[373:org.opendaylight.neutron.northbound-api:0.6.0.SNAPSHOT]
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[:1.7.0_79]
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)[:1.7.0_79]
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[:1.7.0_79]
>         at java.lang.reflect.Method.invoke(Method.java:606)[:1.7.0_79]
>         at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)[195:com.sun.jersey.jersey-server:1.17.0]
>         at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)[195:com.sun.jersey.jersey-server:1.17.0]
>         at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)[195:com.sun.jersey.jersey-server:1.17.0]
>         at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)[195:com.sun.jersey.jersey-server:1.17.0]
>         at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)[195:com.sun.jersey.jersey-server:1.17.0]
>         at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)[195:com.sun.jersey.jersey-server:1.17.0]
>         at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)[195:com.sun.jersey.jersey-server:1.17.0]
>         at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)[195:com.sun.jersey.jersey-server:1.17.0]
>         at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1511)[195:com.sun.jersey.jersey-server:1.17.0]
>         at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1442)[195:com.sun.jersey.jersey-server:1.17.0]
>         at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1391)[195:com.sun.jersey.jersey-server:1.17.0]
>         at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1381)[195:com.sun.jersey.jersey-server:1.17.0]
>         at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)[196:com.sun.jersey.servlet:1.17.0]
>         at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:538)[196:com.sun.jersey.servlet:1.17.0]
>         at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:716)[196:com.sun.jersey.servlet:1.17.0]
>         at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)[159:org.apache.geronimo.specs.geronimo-servlet_3.0_spec:1.0.0]
>         at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)[165:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1496)[165:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:247)[165:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:210)[165:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1467)[165:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)[165:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:69)[174:org.ops4j.pax.web.pax-web-jetty:3.1.4]
>         at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)[165:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)[165:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)[165:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)[165:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:240)[174:org.ops4j.pax.web.pax-web-jetty:3.1.4]
>         at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)[165:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)[165:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)[165:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)[165:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:75)[174:org.ops4j.pax.web.pax-web-jetty:3.1.4]
>         at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)[165:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.server.Server.handle(Server.java:370)[165:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)[165:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982)[165:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043)[165:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)[165:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)[165:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)[165:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)[165:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)[165:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)[165:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)[165:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at java.lang.Thread.run(Thread.java:745)[:1.7.0_79]

Change-Id: Ie2d328adbc80d1279eb8562c7882790fb3ccc236
Signed-off-by: Isaku Yamahata <isaku.yamahata@intel.com>