Updated releng/autorelease Project: bgpcep  5fa8edffc21982d0bc4444bc3fe9895fa9e3ef64
BUG-4531: Error channelFactory set already

When we change the MD5 password we see
IllegalStateException: channelFactory set already.
Fix by setting only once the channelFactory, according
the case, MD5ServerChannelFactory when MD5 instead of
NioServerSocketChannel.

Change-Id: I5d02b1a3e325f1cd47099ee13397d141105969a3
Signed-off-by: Claudio D. Gasparini <cgaspari@cisco.com>