Updated git submodules
Project: netvirt stable/carbon a66d5ee06c599fd77076eff784dcdfb649afd01b

NETVIRT-937: Fix NPE in ElanInstanceManager

2017-11-21 16:21:43,179 | ERROR | nPool-1-worker-2 | JobCoordinatorImpl               | 261 - org.opendaylight.infrautils.jobcoordinator-impl - 1.3.0.SNAPSHOT | Runnnable likely about to terminate thread due to uncaught exception; but here is useful debugging context: JobEntry{key='elaninterface-963a4d35-297e-4757-be14-6c3dec354221', mainWorker=org.opendaylight.netvirt.elan.internal.ElanInstanceManagerElanInstanceManager$$Lambda$774/1098386956@516cbba2, rollbackWorker=null, retryCount=6, futures=[null, com.google.common.util.concurrent.ImmediateFuture$ImmediateSuccessfulCheckedFuture@39325841]}
java.lang.NullPointerException: at index 0
	at com.google.common.collect.ObjectArrays.checkElementNotNull(ObjectArrays.java:235)[27:com.google.guava:22.0.0]
	at com.google.common.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:225)[27:com.google.guava:22.0.0]
	at com.google.common.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:219)[27:com.google.guava:22.0.0]
	at com.google.common.collect.ImmutableList.construct(ImmutableList.java:342)[27:com.google.guava:22.0.0]
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:257)[27:com.google.guava:22.0.0]
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:228)[27:com.google.guava:22.0.0]
	at com.google.common.util.concurrent.Futures.allAsList(Futures.java:835)[27:com.google.guava:22.0.0]
	at org.opendaylight.infrautils.jobcoordinator.internal.JobCoordinatorImpl$MainTask.runWithUncheckedExceptionLogging(JobCoordinatorImpl.java:369)[261:org.opendaylight.infrautils.jobcoordinator-impl:1.3.0.SNAPSHOT]

The futures List in remove is reused across the submitted jobs in the forEach loop
which is unsafe as the List is accessed by multiple threads. Each job now returns its
own local futures List.

The futures returned from elanInterfaceManager.removeElanInterface
were also added to the List but I don't see the purpose of this. removeElanInterface
waits for those tx's to complete. Maybe it was so the JC would retry them? If so, this
entire code path has a mix of sync and async transactions which is a bit confusing -
some are submitted to the JC, ohers aren't; some may be retried, others aren't.

Change-Id: I82193fc36a339db42b83df5bfa3d17ff0a88dfa0
Signed-off-by: Tom Pantelis <tompantelis@gmail.com>
Signed-off-by: Sam Hague <shague@redhat.com>


Fix NPE in VpnSubnetRouteHandler

CSIT log shows several of these:

2017-11-21 16:51:37,973 | ERROR | nPool-1-worker-0 | VpnSubnetRouteHandler            | 349 - org.opendaylight.netvirt.vpnmanager-impl - 0.6.0.SNAPSHOT | SUBNETROUTE: onInterfaceDown: SubnetOpDataEntry update on interface 174fcd9a-f2fc-4f70-bc1e-9a42755175ea down event for subnet 9189b34e-b7be-40ff-9bd4-8c0d0a4f96f3 falied {}
java.lang.NullPointerException
	at org.opendaylight.netvirt.vpnmanager.VpnSubnetRouteHandler.electNewDpnForSubnetRoute(VpnSubnetRouteHandler.java:988)
	at org.opendaylight.netvirt.vpnmanager.VpnSubnetRouteHandler.onInterfaceDown(VpnSubnetRouteHandler.java:649)
	at org.opendaylight.netvirt.vpnmanager.SubnetRouteInterfaceStateChangeListener.lambda$remove$1(SubnetRouteInterfaceStateChangeListener.java:154)

networkId is purposely passed as null in several call sites. It is only used to extract
the String value to pass to addSubnetRouteToFib which passes to L3vpnInput#setNetworkName.
From there is looks like null network name is handled.

Change-Id: Ie86c2ead79d4431a06e04526dc415f58c893d461
Signed-off-by: Tom Pantelis <tompantelis@gmail.com>
Signed-off-by: Sam Hague <shague@redhat.com>


Fix NPE in SubnetmapChangeListener

CSIT log shows a ton of these:

java.lang.NullPointerException
	at org.opendaylight.netvirt.vpnmanager.SubnetmapChangeListener.update(SubnetmapChangeListener.java:119)[349:org.opendaylight.netvirt.vpnmanager-impl:0.6.0.SNAPSHOT]
	at org.opendaylight.netvirt.vpnmanager.SubnetmapChangeListener.update(SubnetmapChangeListener.java:31)[349:org.opendaylight.netvirt.vpnmanager-impl:0.6.0.SNAPSHOT]
	at org.opendaylight.genius.datastoreutils.AsyncDataTreeChangeListenerBase$DataTreeChangeHandler.run(AsyncDataTreeChangeListenerBase.java:152)[247:org.opendaylight.genius.mdsalutil-api:0.4.0.SNAPSHOT]

Either vpnIdOld or subnetId was null when calling getValue(). We could check for
null in all places they're being logged but I just changed it to pass the
reference as Uuid's toString will print the internal value.

Change-Id: I6c88177a476f38c38189bddfb55a62cfba61d9a9
Signed-off-by: Tom Pantelis <tompantelis@gmail.com>
Signed-off-by: Sam Hague <shague@redhat.com>