Updated releng/autorelease Project: groupbasedpolicy  2f92c6e894b7857381ecab697c7c64c7181dcf13
Bug 5102 - NoSuchMethodError in EndpointManager

- keySet method in ConcurrentHashMap changed in Java 8.
- error occurend when the code was built with Java 8 and
  ran on Java 7.
- fixed by compatible interface ConcurrentMap

Change-Id: I672f7102db8b9b3874d1f18419dd01bff3064704
Signed-off-by: Tomas Cechvala <tcechval@cisco.com>