Updated git submodules
Project: neutron master 80f93926e90428256319f8f265176a2a458767ed

Merge "Bug 4815 - Server error with transaction chain failed"

Bug 4815 - Server error with transaction chain failed

Depending on condition, neutron northbound returns Server Error 500
with the following exception. This is because the retry logic
in AbstractNeutronInterface is not correct.
Transaction chain can't be used after transaction aborted. So this patch
moves up the retry logic and re-create transaction on transaction abort.

> 2015-12-16 15:15:16,429 | ERROR | neutron/networks | ContainerResponse                | 47 - com.sun.jersey.jersey-server - 1.17.0 | The RuntimeException could not be mapped to a response, re-throwing to the HTTP container
> java.lang.IllegalStateException: Transaction chain has failed
>         at org.opendaylight.controller.sal.core.spi.data.AbstractSnapshotBackedTransactionChain$Shutdown.getSnapshot(AbstractSnapshotBackedTransactionChain.java:93)
>         at org.opendaylight.controller.sal.core.spi.data.AbstractSnapshotBackedTransactionChain.getSnapshot(AbstractSnapshotBackedTransactionChain.java:113)
>         at org.opendaylight.controller.sal.core.spi.data.AbstractSnapshotBackedTransactionChain.newWriteOnlyTransaction(AbstractSnapshotBackedTransactionChain.java:158)
>         at org.opendaylight.controller.cluster.datastore.LocalTransactionChain.newWriteOnlyTransaction(LocalTransactionChain.java:76)
>         at org.opendaylight.controller.cluster.datastore.AbstractTransactionContextFactory.createLocalTransactionContext(AbstractTransactionContextFactory.java:209)
>         at org.opendaylight.controller.cluster.datastore.AbstractTransactionContextFactory.maybeCreateLocalTransactionContext(AbstractTransactionContextFactory.java:58)
>         at org.opendaylight.controller.cluster.datastore.AbstractTransactionContextFactory.onFindPrimaryShardSuccess(AbstractTransactionContextFactory.java:73)
>         at org.opendaylight.controller.cluster.datastore.AbstractTransactionContextFactory.newTransactionContextWrapper(AbstractTransactionContextFactory.java:99)
>         at org.opendaylight.controller.cluster.datastore.TransactionProxy.getContextWrapper(TransactionProxy.java:317)
>         at org.opendaylight.controller.cluster.datastore.TransactionProxy.getContextWrapper(TransactionProxy.java:308)
>         at org.opendaylight.controller.cluster.datastore.TransactionProxy.merge(TransactionProxy.java:159)
>         at org.opendaylight.controller.cluster.databroker.AbstractDOMBrokerWriteTransaction.merge(AbstractDOMBrokerWriteTransaction.java:95)
>         at org.opendaylight.controller.md.sal.binding.impl.BindingDOMWriteTransactionAdapter.ensureParentsByMerge(BindingDOMWriteTransactionAdapter.java:67)
>         at org.opendaylight.controller.md.sal.binding.impl.AbstractWriteTransaction.put(AbstractWriteTransaction.java:41)
>         at org.opendaylight.neutron.transcriber.AbstractNeutronInterface.updateMd(AbstractNeutronInterface.java:177)
>         at org.opendaylight.neutron.transcriber.AbstractNeutronInterface.addMd(AbstractNeutronInterface.java:151)
>         at org.opendaylight.neutron.transcriber.AbstractNeutronInterface.add(AbstractNeutronInterface.java:360)
>         at org.opendaylight.neutron.transcriber.AbstractNeutronInterface$8.action(AbstractNeutronInterface.java:370)
>         at org.opendaylight.neutron.transcriber.AbstractNeutronInterface$8.action(AbstractNeutronInterface.java:367)
>         at org.opendaylight.neutron.transcriber.AbstractNeutronInterface.chainWrapper1(AbstractNeutronInterface.java:94)
>         at org.opendaylight.neutron.transcriber.AbstractNeutronInterface.add(AbstractNeutronInterface.java:366)
>         at org.opendaylight.neutron.northbound.api.AbstractNeutronNorthboundIAware.create(AbstractNeutronNorthboundIAware.java:94)[235:org.opendaylight.neutron.northbound-api:0.6.0.SNAPSHOT]
>         at org.opendaylight.neutron.northbound.api.NeutronNetworksNorthbound.createNetworks(NeutronNetworksNorthbound.java:239)[235:org.opendaylight.neutron.northbound-api:0.6.0.SNAPSHOT]
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[:1.8.0_72-internal]
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)[:1.8.0_72-internal]
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[:1.8.0_72-internal]
>         at java.lang.reflect.Method.invoke(Method.java:498)[:1.8.0_72-internal]
>         at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)[47:com.sun.jersey.jersey-server:1.17.0]
>         at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)[47:com.sun.jersey.jersey-server:1.17.0]
>         at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)[47:com.sun.jersey.jersey-server:1.17.0]
>         at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)[47:com.sun.jersey.jersey-server:1.17.0]
>         at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)[47:com.sun.jersey.jersey-server:1.17.0]
>         at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)[47:com.sun.jersey.jersey-server:1.17.0]
>         at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)[47:com.sun.jersey.jersey-server:1.17.0]
>         at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1511)[47:com.sun.jersey.jersey-server:1.17.0]
>         at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1442)[47:com.sun.jersey.jersey-server:1.17.0]
>         at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1391)[47:com.sun.jersey.jersey-server:1.17.0]
>         at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1381)[47:com.sun.jersey.jersey-server:1.17.0]
>         at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)[174:com.sun.jersey.servlet:1.17.0]
>         at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:538)[174:com.sun.jersey.servlet:1.17.0]
>         at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:716)[174:com.sun.jersey.servlet:1.17.0]
>         at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)[142:org.apache.geronimo.specs.geronimo-servlet_3.0_spec:1.0.0]
>         at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1496)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:247)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:210)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1467)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:69)[157:org.ops4j.pax.web.pax-web-jetty:3.1.4]
>         at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:240)[157:org.ops4j.pax.web.pax-web-jetty:3.1.4]
>         at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:75)[157:org.ops4j.pax.web.pax-web-jetty:3.1.4]
>         at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.server.Server.handle(Server.java:366)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at java.lang.Thread.run(Thread.java:745)[:1.8.0_72-internal]
>         at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:240)[157:org.ops4j.pax.web.pax-web-jetty:3.1.4]
>         at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:75)[157:org.ops4j.pax.web.pax-web-jetty:3.1.4]
>         at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.server.Server.handle(Server.java:366)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at java.lang.Thread.run(Thread.java:745)[:1.8.0_72-internal]

Change-Id: I3b6127bc9c395360a5bf408402734279015def0d
Signed-off-by: Isaku Yamahata <isaku.yamahata@intel.com>