Updated git submodules
Project: bgpcep stable/beryllium 59f85875ce61dff020369dbffd3a9fcd90276750

Fix unit test regression after netty version bump

Fixed:
java.lang.UnsupportedOperationException: direct buffer
at io.netty.buffer.UnpooledUnsafeDirectByteBuf.array(UnpooledUnsafeDirectByteBuf.java:198)

Direct buffer do not have a backing byte array, use utility function
instead.

Change-Id: I5317255bbbca733181a7dcb477ee30449757f0e7
Signed-off-by: Milos Fabian <milfabia@cisco.com>
(cherry picked from commit 5bbc03c2af2933b1f85bea60fd4c73087c3adb23)