Updated git submodules
Project: yangtools master 89b756f4e548435867beb95c5cabf8fd43fd60c0

Must always use mockito-core instead of mockito-all 

to prevent NoSuchMethodError: org.hamcrest.Matcher ...

Bug 7662 related
Change-Id: Ia34e4f4d0bf5a03cc311d69c3d9cfbe5362521ed
Signed-off-by: Michael Vorburger <vorburger@redhat.com>