Updated git submodules
Project: netvirt master e1be36e69891c8949ea4f0816be9572f9bafb9c2

Fix the fix for the bad transaction leak in VpnInterfaceManager

In 0c3a7e3103fea3dc039519ab4d4497fd218dc3d8 for
I0f62fcc17c037365c9384e56c9f6f5a430693c20 there was a left-over
tx.submit() that should have also been removed as part of it (because
callWithNewWriteOnlyTransactionAndSubmit already does that, as its name
says).  This fixes the follow new error which started appearing in CSIT
logs since that was merged:

2017-11-21 18:05:05,592 | ERROR | ChangeHandler-77 | L3vpnPopulator
| 349 - org.opendaylight.netvirt.vpnmanager-impl - 0.6.0.SNAPSHOT |
Future (eventually) failed: addToLabelMapper
java.lang.UnsupportedOperationException: submit() cannot be used inside
a Managed[New]TransactionRunner

see https://jira.opendaylight.org/browse/NETVIRT-985

Change-Id: Ic2c8b02670242f3a3f190860c205d7d70c2939b3
Signed-off-by: Michael Vorburger <vorburger@redhat.com>