Updated git submodules
Project: netvirt master 4ef5c3fdecb2455d0c00632be22e15b0c7383cd5

Merge "Fix completely broken ElanStatusMonitor JMX MBean"

Fix completely broken ElanStatusMonitor JMX MBean

including a test for future non-regression of this problem:

javax.management.NotCompliantMBeanException: MBean class
org.opendaylight.netvirt.elan.statusanddiag.ElanStatusMonitorJMX does
not implement DynamicMBean, and neither follows the Standard MBean
conventions (javax.management.NotCompliantMBeanException: Class
org.opendaylight.netvirt.elan.statusanddiag.ElanStatusMonitorJMX is not
a JMX compliant Standard MBean) nor the MXBean conventions
(javax.management.NotCompliantMBeanException:
org.opendaylight.netvirt.elan.statusanddiag.ElanStatusMonitorJMX: Class
org.opendaylight.netvirt.elan.statusanddiag.ElanStatusMonitorJMX is not
a JMX compliant MXBean)
	at
com.sun.jmx.mbeanserver.Introspector.checkCompliance(Introspector.java:176)
	at
com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:317)
	at
com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
	at
org.opendaylight.netvirt.elan.statusanddiag.ElanStatusMonitorJMX.registerMbean(ElanStatusMonitorJMX.java:30)
	at
org.opendaylight.netvirt.elan.statusanddiag.ElanStatusMonitorJMX.init(ElanStatusMonitorJMX.java:24)

Change-Id: Ic269921840effd7ffae1c3c51dba88afd78999d5
Signed-off-by: Michael Vorburger <vorburger@redhat.com>