Update git submodules
* Update controller from branch 'stable/oxygen'
  to 278a1ee5e661a1817902cc1bde44500822808ee8
  - Disable artery max frame size settingd
    
    These were accidently set really large when we were first
    looking at artery a while ago but they blow up with
    java.lang.OutOfMemoryError: Direct buffer memory. So
    set them to the defaults and comment them out.
    
    Change-Id: I92dc150808601271f879bc3917a036b76af8d914
    Signed-off-by: Tom Pantelis <tompantelis@gmail.com>
    (cherry picked from commit f605b10df459b9c9df3c697c610f5e6a71b96a0d)