Update patch set 1
Patch Set 1: Code-Review-1

When I run this script I get an error:

  File "determine-merge-order.py", line 52
    print "continuing ... " + node
                          ^
SyntaxError: Missing parentheses in call to 'print'

Patch-set: 1
Label: Code-Review=-1