Updated releng/autorelease Project: integration  8b48459de4a846213156e81848afe935432b96d4
Fix lispflowmapping RPC CRUD tests

Relative path names are causing the lispflowmapping RPC CRUD tests to
fail with the error message:

    IOError: [Errno 2] No such file or directory:
    u'/opt/variables/lispflowmapping/rpc_add-key_ipv4.json'

Adding the ${CURDIR} variable in front of the path should fix the issue.

Change-Id: I63d7ef22b0aa9a7907cb529dc3440bcba7a2b577
Signed-off-by: Lorand Jakab <lojakab@cisco.com>