Update git submodules
* Update infrautils from branch 'master'
  to 4df54f4c8de8bbd7d4beac2c18128573e9ae3fd6
  - introduce DiagStatusCommandTest
    
    motivated by If9076e6d03ba1b4f14af642e585e50dd4d117392;
    testGetRemoteStatusSummary_IPv6() fails without that Sridhar's fix.
    
    requires ClusterMemberInfoProvider to be non-static for testing.
    
    PS: I locally had a *very* weird issue with this test... for me, both
    IPv4 and IPv6 tests fail locally when I am only on WiFi (with wlp4s0
    inet 192.168.1.124 and inet6 fe80::604:7695:606:652a) as below.  The
    192.168.1.159 in the failure is my enp0s31f6 fixed Ethernet interface,
    which was pulled out / disconnected.  Looks like something cached
    somewhere in the system (OS, not JVM) made JMX try to use that?!
    
    Switching WiFi completely off and not having any networking made the
    test pass locally.  Re-connecting on wired Ethernet both only or in
    addition to WiFi also made it pass.
    
    Curiously, not even a cold machine restart made this problem go away.
    
    Must be something local; should pass on build and for others, more FTR:
    
    java.rmi.ConnectIOException: Exception creating connection to:
    192.168.1.159; nested exception is:
    	java.net.NoRouteToHostException: No route to host (Host unreachable)
    	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:631)
    	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:216)
    	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:202)
    	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:129)
    	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(Unknown
    Source)
    	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2430)
    	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:308)
    	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270)
    	at org.opendaylight.infrautils.diagstatus.MBeanUtils.invokeRemoteMBeanOperation(MBeanUtils.java:159)
    	at org.opendaylight.infrautils.diagstatus.shell.DiagStatusCommand.getRemoteStatusSummary(DiagStatusCommand.java:91)
    	at org.opendaylight.infrautils.diagstatus.shell.DiagStatusCommandTest.checkGetRemoteStatusSummary(DiagStatusCommandTest.java:54)
    	at org.opendaylight.infrautils.diagstatus.shell.DiagStatusCommandTest.testGetRemoteStatusSummary_IPv4(DiagStatusCommandTest.java:30)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
    	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
    	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
    	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
    	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
    Caused by: java.net.NoRouteToHostException: No route to host (Host
    unreachable)
    	at java.net.PlainSocketImpl.socketConnect(Native Method)
    	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
    	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
    	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
    	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    	at java.net.Socket.connect(Socket.java:589)
    	at java.net.Socket.connect(Socket.java:538)
    	at java.net.Socket.<init>(Socket.java:434)
    	at java.net.Socket.<init>(Socket.java:211)
    	at sun.rmi.transport.proxy.RMIDirectSocketFactory.createSocket(RMIDirectSocketFactory.java:40)
    	at sun.rmi.transport.proxy.RMIMasterSocketFactory.createSocket(RMIMasterSocketFactory.java:148)
    	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:613)
    	... 34 more
    
    Change-Id: I545195b1b976f5951d2dc8e9599e7ab33bc407e9
    Signed-off-by: Michael Vorburger <vorburger@redhat.com>