Updated git submodules
Project: mdsal master 65d7b01d373eb6736e55ff96846fff76af5a1adf

Fix NoSuchMethodError in Eclipse IDE by removing M2E lifecycle mapping

This is no longer required with
https://github.com/vorburger/opendaylight-eclipse-setup

This FIXES Execution check-license of goal
org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check failed: An
API incompatibility was encountered while executing
org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check:
java.lang.NoSuchMethodError:
org.slf4j.spi.LocationAwareLogger.log(Lorg/slf4j/Marker;Ljava/lang/String;ILjava/lang/String;Ljava/lang/Throwable;)V

Change-Id: I6cbe65013a50e2178b7fda99701e02cd40880d62
Signed-off-by: Michael Vorburger <vorburger@redhat.com>