Updated releng/autorelease Project: ovsdb  3badc733ce4582990f9fa6014f3ce7ef57c17ef3
Bug 4045 - ipv6 work around

When running tempest, the following exceptions occurs because
ipv6 is not supported yet. This patch is work around for now.
TODO: support IPv6 and remove this work around

> 2015-08-25 15:00:12,428 | ERROR | ntDispatcherImpl | EventDispatcher                  | 400 - org.opendaylight.ovsdb.openstack.net-virt - 1.2.0.SNAPSHOT | Exception in dispatching event NorthboundEvent [handler=NEUTRON_ROUTER, action=DELETE, port=null, subnet=null, router=NeutronRouter [id=55dc4fd2-0e5f-4ec8-b589-18616dfaa6a1, name=tempest-router--44999886, adminStateUp=false, status=ACTIVE, tenantID=86d8df7573f24bc68e0a75846812839d, external_gateway_info=NeutronRouterNetworkReference [networkID=7d526ede-cfd0-45ec-897f-607471dd801e enableSNAT=true externalFixedIPs=[Neutron_IPs{ipAddress='172.24.4.62', subnetUUID='9a799aec-5f1f-4a2d-b3ed-a109f6c89bcb'}, Neutron_IPs{ipAddress='2001:db8::3e', subnetUUID='5178fb71-6683-4cf6-a1e7-095da5b9962a'}]], distributed=false, gw_port_id=2419ec70-21e8-4a3b-aa52-82ec9dd7f698, routes=[], interfaces={}], routerInterface=NeutronRouterInterface [subnetUUID=009ab797-30df-4c55-87f4-5142a9f8b444, portUUID=900abbc5-4db9-4bec-8777-0018f2950751, id=55dc4fd2-0e5f-4ec8-b589-18616dfaa6a1, tenantID=86d8df7573f24bc68e0a75846812839d], floatingIP=null, network=null, loadBalancer=null, loadBalancerPool=null, loadBalancerPoolMember=null]
> java.lang.IllegalArgumentException: Supplied value "fdfd:7da6:14e6:0:f816:3eff:fe43:c114/32" does not match required pattern "^(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])/(([0-9])|([1-2][0-9])|(3[0-2]))$"
>         at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)[39:com.google.guava:18.0.0]
>         at org.opendaylight.yang.gen.v1.urn.ietf.params.xml.ns.yang.ietf.inet.types.rev100924.Ipv4Prefix.<init>(Ipv4Prefix.java:49)[49:org.opendaylight.yangtools.model.ietf-inet-types:2010.9.24.8-SNAPSHOT]
>         at org.opendaylight.ovsdb.utils.mdsal.openflow.MatchUtils.iPv4PrefixFromIPv4Address(MatchUtils.java:1133)[401:org.opendaylight.ovsdb.openstack.net-virt-providers:1.2.0.SNAPSHOT]
>         at org.opendaylight.ovsdb.openstack.netvirt.providers.openflow13.services.L3ForwardingService.programForwardingTableEntry(L3ForwardingService.java:64)[401:org.opendaylight.ovsdb.openstack.net-virt-providers:1.2.0.SNAPSHOT]
>         at org.opendaylight.ovsdb.openstack.netvirt.impl.NeutronL3Adapter.programL3ForwardingStage2(NeutronL3Adapter.java:689)[400:org.opendaylight.ovsdb.openstack.net-virt:1.2.0.SNAPSHOT]
>         at org.opendaylight.ovsdb.openstack.netvirt.impl.NeutronL3Adapter.programL3ForwardingStage1(NeutronL3Adapter.java:670)[400:org.opendaylight.ovsdb.openstack.net-virt:1.2.0.SNAPSHOT]
>         at org.opendaylight.ovsdb.openstack.netvirt.impl.NeutronL3Adapter.updateL3ForNeutronPort(NeutronL3Adapter.java:640)[400:org.opendaylight.ovsdb.openstack.net-virt:1.2.0.SNAPSHOT]
>         at org.opendaylight.ovsdb.openstack.netvirt.impl.NeutronL3Adapter.handleNeutronRouterInterfaceEvent(NeutronL3Adapter.java:310)[400:org.opendaylight.ovsdb.openstack.net-virt:1.2.0.SNAPSHOT]
>         at org.opendaylight.ovsdb.openstack.netvirt.RouterHandler.processEvent(RouterHandler.java:208)[400:org.opendaylight.ovsdb.openstack.net-virt:1.2.0.SNAPSHOT]
>         at org.opendaylight.ovsdb.openstack.netvirt.impl.EventDispatcherImpl.dispatchEvent(EventDispatcherImpl.java:95)[400:org.opendaylight.ovsdb.openstack.net-virt:1.2.0.SNAPSHOT]
>         at org.opendaylight.ovsdb.openstack.netvirt.impl.EventDispatcherImpl.access$200(EventDispatcherImpl.java:28)[400:org.opendaylight.ovsdb.openstack.net-virt:1.2.0.SNAPSHOT]
>         at org.opendaylight.ovsdb.openstack.netvirt.impl.EventDispatcherImpl$1.run(EventDispatcherImpl.java:57)[400:org.opendaylight.ovsdb.openstack.net-virt:1.2.0.SNAPSHOT]
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)[:1.7.0_79]
>         at java.util.concurrent.FutureTask.run(FutureTask.java:262)[:1.7.0_79]
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)[:1.7.0_79]
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)[:1.7.0_79]
>         at java.lang.Thread.run(Thread.java:745)[:1.7.0_79]

Change-Id: If886c3867665660c8f90a72f567420f48f3fd6ad
Signed-off-by: Isaku Yamahata <isaku.yamahata@intel.com>