Updated releng/autorelease Project: odlparent  759499087b5546ee3ea61ed71e1c8ce96b7a924a
Upgrade Apache Shiro Dependency from 1.2.3 to 1.2.4

Upstream documentation of the changes between releases 1.2.3 and 1.2.4 is
located here:

https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12310950&version=12329682

In short, there were five bug fixes between 1.2.3 and 1.2.4, one of which is
security related:

Bug
[SHIRO-517] - Caused by: java.lang.NoClassDefFoundError: Lcom/google/inject/internal/util/$ImmutableList;
[SHIRO-518] - Shiro-CAS: Security Problem in cas-client-core versions older than 3.3.2
Improvement
[SHIRO-332] - Change access level of method 'isPermitted' in org.apache.shiro.realm.AuthorizingRealm (line 461) from private to protected
[SHIRO-496] - Update shior.guice dependency
[SHIRO-498] - ThreadLocal should not be created when not necessary

This was tested and does not seem to present any regressions from Shiro 1.2.3.

Change-Id: I4969fb669f628547804a9071cfe3b89cc4ca4073
Signed-off-by: Ryan Goulding <ryandgoulding@gmail.com>