Updated releng/autorelease Project: groupbasedpolicy  78af3e47debc6971bcf57c21abc62a18d3dd1e51
Bug 5102 - NoSuchMethodError in EndpointManager

- keySet method in ConcurrentHashMap changed in Java 8.
- error occurend when the code was built with Java 8 and
  ran on Java 7.
- fixed by compatible interface ConcurrentMap

Change-Id: I672f7102db8b9b3874d1f18419dd01bff3064704
Signed-off-by: Tomas Cechvala <tcechval@cisco.com>