Updated releng/autorelease Project: yangtools  a0009aaee1803d25d740cd5539797c8724680ba7
Bug 4414: Shorthand case statement not working

Original for shorthand-case was not set at all,
therefore definition in grouping causes
IncorrectNestingException: Supplied class is not valid case

- code refactored
- fix: getOriginal() returns proper value

Change-Id: I6941eea52a07967824d2653fbfaedebc5f35ddc9
Signed-off-by: Martin Ciglan <mciglan@cisco.com>