Updated releng/autorelease Project: neutron  9af2e64c819fcdc4ba82fb64d77d9f6c71bf3eb2
BUG #4044 binding:host_id is string, not UUID

The attributes of ML2 binding extension, binding:host_id, is string.
By default, the host id is determined by gethostname.
It causes the following exception.

> java.lang.IllegalArgumentException: Supplied value "ls" does not match required pattern "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
>         at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
>         at org.opendaylight.yang.gen.v1.urn.ietf.params.xml.ns.yang.ietf.yang.types.rev130715.Uuid.<init>(Uuid.java:44)
>         at org.opendaylight.neutron.transcriber.AbstractNeutronInterface.toUuid(AbstractNeutronInterface.java:100)
>         at org.opendaylight.neutron.transcriber.NeutronPortInterface.toMd(NeutronPortInterface.java:227)
>         at org.opendaylight.neutron.transcriber.NeutronPortInterface.toMd(NeutronPortInterface.java:55)
>         at org.opendaylight.neutron.transcriber.AbstractNeutronInterface.updateMd(AbstractNeutronInterface.java:75)
>         at org.opendaylight.neutron.transcriber.NeutronPortInterface.updatePort(NeutronPortInterface.java:182)
>         at org.opendaylight.neutron.northbound.api.NeutronPortsNorthbound.updatePort(NeutronPortsNorthbound.java:473)[373:org.opendaylight.neutron.northbound-api:0.6.0.SNAPSHOT]
>         at sun.reflect.GeneratedMethodAccessor210.invoke(Unknown Source)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[:1.7.0_79]
>         at java.lang.reflect.Method.invoke(Method.java:606)[:1.7.0_79]
>         at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)[195:com.sun.jersey.jersey-server:1.17.0]
>         at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)[195:com.sun.jersey.jersey-server:1.17.0]
>         at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)[195:com.sun.jersey.jersey-server:1.17.0]
>         at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)[195:com.sun.jersey.jersey-server:1.17.0]
>         at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)[195:com.sun.jersey.jersey-server:1.17.0]
>         at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)[195:com.sun.jersey.jersey-server:1.17.0]
>         at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)[195:com.sun.jersey.jersey-server:1.17.0]
>         at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)[195:com.sun.jersey.jersey-server:1.17.0]
>         at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1511)[195:com.sun.jersey.jersey-server:1.17.0]
>         at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1442)[195:com.sun.jersey.jersey-server:1.17.0]
>         at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1391)[195:com.sun.jersey.jersey-server:1.17.0]
>         at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1381)[195:com.sun.jersey.jersey-server:1.17.0]
>         at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)[196:com.sun.jersey.servlet:1.17.0]
>         at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:538)[196:com.sun.jersey.servlet:1.17.0]
>         at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:716)[196:com.sun.jersey.servlet:1.17.0]
>         at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)[159:org.apache.geronimo.specs.geronimo-servlet_3.0_spec:1.0.0]
>         at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)[165:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1496)[165:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:247)[165:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:210)[165:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1467)[165:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)[165:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:69)[174:org.ops4j.pax.web.pax-web-jetty:3.1.4]
>         at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)[165:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)[165:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)[165:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)[165:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:240)[174:org.ops4j.pax.web.pax-web-jetty:3.1.4]
>         at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)[165:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)[165:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)[165:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)[165:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:75)[174:org.ops4j.pax.web.pax-web-jetty:3.1.4]
>         at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)[165:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.server.Server.handle(Server.java:370)[165:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)[165:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982)[165:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043)[165:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)[165:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)[165:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)[165:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)[165:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)[165:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)[165:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)[165:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at java.lang.Thread.run(Thread.java:745)[:1.7.0_79]

Change-Id: Ic61ba6188ebec597cee55cc34e231690a995daa6
Signed-off-by: Isaku Yamahata <isaku.yamahata@intel.com>