Update git submodules
* Update netconf from branch 'master'
  to ef83a540dea96885fba15f1471c16e2f67c969de
  - Unwanted commit to non candidate device fix
    
    - netconf is sending commits to non candidate devices
      while editing their running config which results into
      NetconfDocumentedException: Unknown element "commit".
    
    JIRA: NETCONF-755
    Signed-off-by: mhurban <mar.hurban@gmail.com>
    Change-Id: I536b43394269c4dd5223e4322ae830b813016ff0
    (cherry picked from commit bf199d0da1729e4e68ad4059cfa8089d70d1932f)