Updated releng/autorelease Project: bgpcep  a921309a99c7efe906ab5d2811e4f9e4881397c6
Remove gracefullyShutdown of EventLoopGroops

When instance is closed, boosgroud and workergroop
shouldnt be shutdown since they are required in case
of new instance created. If new instance is created
it will cause
RejectedExecutionException: event executor terminated

Change-Id: I58f9328140bc209aeafc7bfad14f883887447a59
Signed-off-by: Claudio D. Gasparini <cgaspari@cisco.com>