Updated releng/autorelease Project: neutron  8565c3d779da58faa06fac75096c673eef75661f
Bug 4745 - extra dhcp opt: neutron API updated to include ip_version

Exception occurs as follows with the context of extra_dhcp_opts.
Neutron API of extra_dhcp_opts added ip_version to distinguish ipv4 and ip6.
It needs to be handled, otherwise exception occurs.

create/update port with extra_dhcp_opts
    "extra_dhcp_opts": [
      {
        "opt_value": "pxelinux.0",
        "ip_version": 4,
        "opt_name": "bootfile-name"
      },
      {
        "opt_value": "123.123.123.45",
        "ip_version": 4,
        "opt_name": "server-ip-address"
      },
      {
        "opt_value": "123.123.123.123",
        "ip_version": 4,
        "opt_name": "tftp-server"
      }

> 2015-12-08 10:06:30,307 | ERROR | v2/neutron/ports | ContainerResponse                | 47 - com.sun.jersey.jersey-server - 1.17.0 | The RuntimeException could not be mapped to a response, re-throwing to the HTTP container
> java.lang.IllegalArgumentException: All keys must be specified for class org.opendaylight.yang.gen.v1.urn.opendaylight.neutron.ports.rev150712.port.attributes.ExtraDhcpOptsKey. Missing key is getIpVersion. Supplied key is ExtraDhcpOptsKey [_optName=bootfile-na
> me]
>         at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
>         at org.opendaylight.yangtools.binding.data.codec.impl.ValueContext.getAndSerialize(ValueContext.java:46)
>         at org.opendaylight.yangtools.binding.data.codec.impl.IdentifiableItemCodec.serialize(IdentifiableItemCodec.java:124)
>         at org.opendaylight.yangtools.binding.data.codec.impl.IdentifiableItemCodec.serialize(IdentifiableItemCodec.java:31)
>         at org.opendaylight.yangtools.binding.data.codec.impl.KeyedListNodeCodecContext.serialize(KeyedListNodeCodecContext.java:80)
>         at org.opendaylight.yangtools.binding.data.codec.impl.BindingToNormalizedStreamWriter.startMapEntryNode(BindingToNormalizedStreamWriter.java:156)
>         at org.opendaylight.yang.gen.v1.urn.opendaylight.neutron.ports.rev150712.port.attributes.ExtraDhcpOpts$StreamWriter.serialize(DataObjectSerializerPrototype.java)
>         at org.opendaylight.yang.gen.v1.urn.opendaylight.neutron.ports.rev150712.ports.attributes.ports.Port$StreamWriter.serialize(DataObjectSerializerPrototype.java)
>         at org.opendaylight.yangtools.binding.data.codec.impl.BindingNormalizedNodeCodecRegistry$DataObjectSerializerProxy.serialize(BindingNormalizedNodeCodecRegistry.java:295)
>         at org.opendaylight.yangtools.binding.data.codec.impl.BindingNormalizedNodeCodecRegistry.toNormalizedNode(BindingNormalizedNodeCodecRegistry.java:106)
>         at org.opendaylight.controller.md.sal.binding.impl.BindingToNormalizedNodeCodec.toNormalizedNode(BindingToNormalizedNodeCodec.java:133)
>         at org.opendaylight.controller.md.sal.binding.impl.AbstractWriteTransaction.put(AbstractWriteTransaction.java:39)
>         at org.opendaylight.neutron.transcriber.AbstractNeutronInterface.updateMd(AbstractNeutronInterface.java:177)
>         at org.opendaylight.neutron.transcriber.AbstractNeutronInterface.addMd(AbstractNeutronInterface.java:151)
>         at org.opendaylight.neutron.transcriber.AbstractNeutronInterface.add(AbstractNeutronInterface.java:360)
>         at org.opendaylight.neutron.transcriber.AbstractNeutronInterface$8.action(AbstractNeutronInterface.java:370)
>         at org.opendaylight.neutron.transcriber.AbstractNeutronInterface$8.action(AbstractNeutronInterface.java:367)
>         at org.opendaylight.neutron.transcriber.AbstractNeutronInterface.chainWrapper1(AbstractNeutronInterface.java:94)
>         at org.opendaylight.neutron.transcriber.AbstractNeutronInterface.add(AbstractNeutronInterface.java:366)
>         at org.opendaylight.neutron.northbound.api.AbstractNeutronNorthboundIAware.create(AbstractNeutronNorthboundIAware.java:64)[235:org.opendaylight.neutron.northbound-api:0.6.0.SNAPSHOT]
>         at org.opendaylight.neutron.northbound.api.NeutronPortsNorthbound.createPorts(NeutronPortsNorthbound.java:247)[235:org.opendaylight.neutron.northbound-api:0.6.0.SNAPSHOT]
>         at sun.reflect.GeneratedMethodAccessor99.invoke(Unknown Source)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[:1.8.0_45-internal]
>         at java.lang.reflect.Method.invoke(Method.java:497)[:1.8.0_45-internal]
>         at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)[47:com.sun.jersey.jersey-server:1.17.0]
>         at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)[47:com.sun.jersey.jersey-server:1.17.0]
>         at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)[47:com.sun.jersey.jersey-server:1.17.0]
>         at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)[47:com.sun.jersey.jersey-server:1.17.0]
>         at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)[47:com.sun.jersey.jersey-server:1.17.0]
>         at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)[47:com.sun.jersey.jersey-server:1.17.0]
>         at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)[47:com.sun.jersey.jersey-server:1.17.0]
>         at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1511)[47:com.sun.jersey.jersey-server:1.17.0]
>         at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1442)[47:com.sun.jersey.jersey-server:1.17.0]
>         at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1391)[47:com.sun.jersey.jersey-server:1.17.0]
>         at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1381)[47:com.sun.jersey.jersey-server:1.17.0]
>         at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)[174:com.sun.jersey.servlet:1.17.0]
>         at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:538)[174:com.sun.jersey.servlet:1.17.0]
>         at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:716)[174:com.sun.jersey.servlet:1.17.0]
>         at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)[142:org.apache.geronimo.specs.geronimo-servlet_3.0_spec:1.0.0]
>         at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1496)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:247)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:210)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1467)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:69)[157:org.ops4j.pax.web.pax-web-jetty:3.1.4]
>         at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:240)[157:org.ops4j.pax.web.pax-web-jetty:3.1.4]
>         at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:75)[157:org.ops4j.pax.web.pax-web-jetty:3.1.4]
>         at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.server.Server.handle(Server.java:366)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
>         at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)[148:org.eclipse.jetty.aggregate.jetty-all-server:8.

Change-Id: I6f2713ad6baedd60be58dbd38ca420906157810a
Signed-off-by: Isaku Yamahata <isaku.yamahata@intel.com>